component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/changes/.*
- ./bin/java/.*
- ./bin/java/org/.*
- ./bin/java/org/apache/.*
- ./bin/java/org/apache/velocity/.*
- ./bin/java/org/apache/velocity/anakia/.*
- ./bin/java/org/apache/velocity/app/.*
- ./bin/java/org/apache/velocity/app/event/.*
- ./bin/java/org/apache/velocity/app/event/implement/.*
- ./bin/java/org/apache/velocity/app/tools/.*
- ./bin/java/org/apache/velocity/context/.*
- ./bin/java/org/apache/velocity/convert/.*
- ./bin/java/org/apache/velocity/exception/.*
- ./bin/java/org/apache/velocity/io/.*
- ./bin/java/org/apache/velocity/runtime/.*
- ./bin/java/org/apache/velocity/runtime/defaults/.*
- ./bin/java/org/apache/velocity/runtime/directive/.*
- ./bin/java/org/apache/velocity/runtime/log/.*
- ./bin/java/org/apache/velocity/runtime/parser/.*
- ./bin/java/org/apache/velocity/runtime/parser/node/.*
- ./bin/java/org/apache/velocity/runtime/visitor/.*
- ./bin/java/org/apache/velocity/servlet/.*
- ./bin/java/org/apache/velocity/texen/.*
- ./bin/java/org/apache/velocity/texen/ant/.*
- ./bin/java/org/apache/velocity/texen/defaults/.*
- ./bin/java/org/apache/velocity/texen/util/.*
- ./bin/java/org/apache/velocity/util/.*
- ./bin/java/org/apache/velocity/util/introspection/.*
- ./bin/parser/.*
- ./bin/site/.*
- ./bin/site/apt/.*
- ./bin/test/.*
- ./bin/test/org/.*
- ./bin/test/org/apache/.*
- ./bin/test/org/apache/velocity/.*
- ./bin/test/org/apache/velocity/io/.*
- ./bin/test/org/apache/velocity/test/.*
- ./bin/test/org/apache/velocity/test/eventhandler/.*
- ./bin/test/org/apache/velocity/test/issues/.*
- ./bin/test/org/apache/velocity/test/misc/.*
- ./bin/test/org/apache/velocity/test/provider/.*
- ./bin/test/org/apache/velocity/test/sql/.*
- ./bin/test/org/apache/velocity/test/util/.*
- ./bin/test/org/apache/velocity/test/util/introspection/.*
- ./bin/test/org/apache/velocity/test/view/.*
- ./bin/test/org/apache/velocity/util/.*
- ./build/.*
- ./build/xsl/.*
- ./convert/.*
- ./docs/.*
- ./docs/api/.*
- ./docs/api/org/.*
- ./docs/api/org/apache/.*
- ./docs/api/org/apache/velocity/.*
- ./docs/api/org/apache/velocity/anakia/.*
- ./docs/api/org/apache/velocity/anakia/class-use/.*
- ./docs/api/org/apache/velocity/app/.*
- ./docs/api/org/apache/velocity/app/class-use/.*
- ./docs/api/org/apache/velocity/app/event/.*
- ./docs/api/org/apache/velocity/app/event/class-use/.*
- ./docs/api/org/apache/velocity/app/event/implement/.*
- ./docs/api/org/apache/velocity/app/event/implement/class-use/.*
- ./docs/api/org/apache/velocity/app/tools/.*
- ./docs/api/org/apache/velocity/app/tools/class-use/.*
- ./docs/api/org/apache/velocity/class-use/.*
- ./docs/api/org/apache/velocity/context/.*
- ./docs/api/org/apache/velocity/context/class-use/.*
- ./docs/api/org/apache/velocity/convert/.*
- ./docs/api/org/apache/velocity/convert/class-use/.*
- ./docs/api/org/apache/velocity/exception/.*
- ./docs/api/org/apache/velocity/exception/class-use/.*
- ./docs/api/org/apache/velocity/io/.*
- ./docs/api/org/apache/velocity/io/class-use/.*
- ./docs/api/org/apache/velocity/runtime/.*
- ./docs/api/org/apache/velocity/runtime/class-use/.*
- ./docs/api/org/apache/velocity/runtime/directive/.*
- ./docs/api/org/apache/velocity/runtime/directive/class-use/.*
- ./docs/api/org/apache/velocity/runtime/log/.*
- ./docs/api/org/apache/velocity/runtime/log/class-use/.*
- ./docs/api/org/apache/velocity/runtime/parser/.*
- ./docs/api/org/apache/velocity/runtime/parser/class-use/.*
- ./docs/api/org/apache/velocity/runtime/parser/node/.*
- ./docs/api/org/apache/velocity/runtime/parser/node/class-use/.*
- ./docs/api/org/apache/velocity/runtime/visitor/.*
- ./docs/api/org/apache/velocity/runtime/visitor/class-use/.*
- ./docs/api/org/apache/velocity/servlet/.*
- ./docs/api/org/apache/velocity/servlet/class-use/.*
- ./docs/api/org/apache/velocity/texen/.*
- ./docs/api/org/apache/velocity/texen/ant/.*
- ./docs/api/org/apache/velocity/texen/ant/class-use/.*
- ./docs/api/org/apache/velocity/texen/class-use/.*
- ./docs/api/org/apache/velocity/texen/util/.*
- ./docs/api/org/apache/velocity/texen/util/class-use/.*
- ./docs/api/org/apache/velocity/util/.*
- ./docs/api/org/apache/velocity/util/class-use/.*
- ./docs/api/org/apache/velocity/util/introspection/.*
- ./docs/api/org/apache/velocity/util/introspection/class-use/.*
- ./docs/images/.*
- ./docs/translations/.*
- ./examples/.*
- ./examples/app_example1/.*
- ./examples/app_example2/.*
- ./examples/bin/.*
- ./examples/context_example/.*
- ./examples/event_example/.*
- ./examples/lib/.*
- ./examples/logger_example/.*
- ./examples/xmlapp_example/.*
- ./lib/.*
- ./lib/test/.*
- ./test/.*
- ./test/absolute/.*
- ./test/absolute/compare/.*
- ./test/anakia/.*
- ./test/anakia/compare/.*
- ./test/anakia/xdocs/.*
- ./test/anakia/xdocs/stylesheets/.*
- ./test/classloader/.*
- ./test/configuration/.*
- ./test/configuration/compare/.*
- ./test/cpload/.*
- ./test/cpload/compare/.*
- ./test/ds/.*
- ./test/ds/templates/.*
- ./test/evaluate/.*
- ./test/evaluate/compare/.*
- ./test/includeerror/.*
- ./test/includeevent/.*
- ./test/includeevent/compare/.*
- ./test/includeevent/subdir/.*
- ./test/info/.*
- ./test/issues/.*
- ./test/issues/velocity-537/.*
- ./test/issues/velocity-537/compare/.*
- ./test/issues/velocity-537/templates/.*
- ./test/issues/velocity-580/.*
- ./test/issues/velocity-580/compare/.*
- ./test/issues/velocity-580/templates/.*
- ./test/macroforwarddefine/.*
- ./test/macroforwarddefine/compare/.*
- ./test/macrolibs/.*
- ./test/macrolibs/compare/.*
- ./test/methodoverloading/.*
- ./test/methodoverloading/compare/.*
- ./test/misc/.*
- ./test/multi/.*
- ./test/multi/compare/.*
- ./test/multi/path1/.*
- ./test/multi/path2/.*
- ./test/multiloader/.*
- ./test/multiloader/compare/.*
- ./test/parseexception/.*
- ./test/parsemacros/.*
- ./test/parsemacros/compare/.*
- ./test/set/.*
- ./test/set/compare/.*
- ./test/stringloader/.*
- ./test/stringloader/compare/.*
- ./test/templates/.*
- ./test/templates/compare/.*
- ./test/templates/subdir/.*
- ./test/texen/.*
- ./test/texen/compare/.*
- ./test/texen/templates/.*
- ./test/texen-classpath/.*
- ./test/texen-classpath/compare/.*
- ./test/texen-classpath/jar-contents/.*
- ./xdocs/.*
- ./xdocs/docs/.*
- ./xdocs/docs/translations/.*
- ./xdocs/images/.*
- ./xdocs/stylesheets/.*
